import os
import json

library_json = {
    'name': 'AtmelStart',
    'description': 'Encapsulates code generated by Atmel Start',
    'build': {
        'libArchive': False,
        'srcFilter': [],
        'flags': [
            "!echo \"-Wl,-T$(pwd)/generated/samd21a/gcc/gcc/samd21e18a_flash.ld\"",
            "-Wl,--section-start=.text=0x2000"
        ],
    }
}

script_dir = os.path.dirname(os.path.realpath(__file__))
MAKEFILE = script_dir + '/generated/gcc/Makefile'
LIBRARY_JSON = script_dir + '/library.json'

if not os.path.isfile(MAKEFILE):
    print("MakeFile is missing")

with open(MAKEFILE) as makefile:
    for line in makefile:
        if line.startswith('OBJS'):
            break

    for line in makefile:
        strip = line.strip()
        if not strip:
            break
        path = strip.split('.')[0]
        if path != 'main':
            # Add to sources filter.
            library_json['build']['srcFilter'].append('+<generated/' + path + '.c>')

    for line in makefile:
        if line.startswith('-I'):
            for arg in line.split('-I')[1:]:
                path = arg.split('"')[1]
                # Add to include build flags.
                library_json['build']['flags'].append('-Igenerated/' + path[3:])
            break


with open(LIBRARY_JSON, 'w') as library_json_file:
    library_json_file.write(json.dumps(library_json,  indent=2, sort_keys=True))